# =======================================================
# CONFIGURAÃÂÃÂÃÂÃÂES DO SPRING BOOT (MICROSSERVIÃÂÃÂO GATEWAY)
# =======================================================

# 1. Nome da aplicaÃÂÃÂ§ÃÂÃÂ£o
spring.application.name=HomegaIBKRPONTE

# 2. Porta REST do MicrosserviÃÂÃÂ§o (Para comunicaÃÂÃÂ§ÃÂÃÂ£o HTTP com o App Principal)
server.port=8085

# 3. Path de contexto
spring.web.servlet.context-path=/

# 4. ConfiguraÃÂÃÂ§ÃÂÃÂ£o de Logs
logging.level.root=INFO
logging.level.com.example.homegaibkrponte=DEBUG

# =======================================================
# CONFIGURAÃÂÃÂÃÂÃÂES DA IBKR (PARA O IBKRConnector - SOCKET)
# =======================================================



# AJUSTE: ParÃÂÃÂ¢metro dinÃÂÃÂ¢mico para o Principal (PadrÃÂÃÂ£o: localhost:8080)
#homega.app.webhook.base-url=${PRINCIPAL_URL:http://localhost:8080}
homega.app.webhook.base-url=http://127.0.0.1:8080
webhook.timeout-ms=5000

# =======================================================
# DESATIVAÃÂÃÂÃÂÃÂO DE SEGURANÃÂÃÂA NO MICROSSERVIÃÂÃÂO GATEWAY
# =======================================================

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
                             org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration,\
                             org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

management.security.enabled=false

#api.ibkr.host=127.0.0.1
#live-trading
#api.ibkr.port=4001
#api.ibkr.account-id=U22445775

#ModoTeste
api.ibkr.host=127.0.0.1
api.ibkr.port=4002
api.ibkr.account-id=DUN652604

# ð¡ï¸ ROTA SEGURA: IDs separados para evitar colisÃ£o de comandos
# O ID 115 cuidarÃ¡ apenas dos preÃ§os (Ticks)
# O ID 116 cuidarÃ¡ apenas do saldo e ordens
api.ibkr.clientId.marketData=115
api.ibkr.clientId.account=116

# Fallback para compatibilidade caso o cÃ³digo use a chave antiga
api.ibkr.clientId=115